import { Button } from '@/components/ui/button'
import { Dumbbell, Users, Brain, BarChart3, Star, Check } from 'lucide-react'

export default function HomePage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-primary-50 to-white">
      {/* Header */}
      <header className="container mx-auto px-4 py-6">
        <nav className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <Dumbbell className="h-8 w-8 text-primary-600" />
            <span className="text-2xl font-bold text-gray-900">FitForge</span>
          </div>
          <div className="space-x-4">
            <Button variant="ghost" asChild>
              <a href="/login">Sign In</a>
            </Button>
            <Button asChild>
              <a href="/register">Get Started</a>
            </Button>
          </div>
        </nav>
      </header>

      {/* Hero Section */}
      <section className="container mx-auto px-4 py-20 text-center">
        <h1 className="text-5xl font-bold text-gray-900 mb-6">
          Forge Your Perfect <span className="text-primary-600">Fitness Journey</span>
        </h1>
        <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
          Create personalized workout plans, track your progress, and get AI-powered coaching. 
          Join a community of fitness enthusiasts on the same journey.
        </p>
        <div className="space-x-4">
          <Button size="lg" asChild>
            <a href="/register">Start Free Trial</a>
          </Button>
          <Button variant="outline" size="lg">
            View Demo
          </Button>
        </div>
      </section>

      {/* Features */}
      <section className="container mx-auto px-4 py-20">
        <h2 className="text-3xl font-bold text-center mb-12">Everything you need to succeed</h2>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div className="text-center">
            <div className="bg-primary-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
              <Brain className="h-8 w-8 text-primary-600" />
            </div>
            <h3 className="text-xl font-semibold mb-2">AI Workout Plans</h3>
            <p className="text-gray-600">Get personalized workouts generated by AI based on your goals and equipment.</p>
          </div>
          <div className="text-center">
            <div className="bg-primary-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
              <BarChart3 className="h-8 w-8 text-primary-600" />
            </div>
            <h3 className="text-xl font-semibold mb-2">Progress Tracking</h3>
            <p className="text-gray-600">Track your lifts, monitor progress, and get insights on your performance.</p>
          </div>
          <div className="text-center">
            <div className="bg-primary-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
              <Users className="h-8 w-8 text-primary-600" />
            </div>
            <h3 className="text-xl font-semibold mb-2">Social Community</h3>
            <p className="text-gray-600">Follow friends, share workouts, and stay motivated with community support.</p>
          </div>
          <div className="text-center">
            <div className="bg-primary-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">
              <Star className="h-8 w-8 text-primary-600" />
            </div>
            <h3 className="text-xl font-semibold mb-2">Form Coaching</h3>
            <p className="text-gray-600">Get AI-powered form tips and safety advice for every exercise.</p>
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section className="container mx-auto px-4 py-20">
        <h2 className="text-3xl font-bold text-center mb-12">Choose your plan</h2>
        <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto">
          <div className="bg-white rounded-lg shadow-lg p-8">
            <h3 className="text-2xl font-bold mb-4">Free</h3>
            <div className="text-4xl font-bold mb-6">$0<span className="text-lg font-normal text-gray-600">/month</span></div>
            <ul className="space-y-3 mb-8">
              <li className="flex items-center">
                <Check className="h-5 w-5 text-green-500 mr-3" />
                3 workout plans
              </li>
              <li className="flex items-center">
                <Check className="h-5 w-5 text-green-500 mr-3" />
                Basic progress tracking
              </li>
              <li className="flex items-center">
                <Check className="h-5 w-5 text-green-500 mr-3" />
                Community features
              </li>
              <li className="flex items-center">
                <Check className="h-5 w-5 text-green-500 mr-3" />
                Limited AI usage
              </li>
            </ul>
            <Button className="w-full" variant="outline" asChild>
              <a href="/register">Get Started</a>
            </Button>
          </div>

          <div className="bg-primary-600 text-white rounded-lg shadow-lg p-8">
            <h3 className="text-2xl font-bold mb-4">Pro</h3>
            <div className="text-4xl font-bold mb-6">$12<span className="text-lg font-normal opacity-80">/month</span></div>
            <ul className="space-y-3 mb-8">
              <li className="flex items-center">
                <Check className="h-5 w-5 text-primary-200 mr-3" />
                Unlimited workout plans
              </li>
              <li className="flex items-center">
                <Check className="h-5 w-5 text-primary-200 mr-3" />
                Full AI features
              </li>
              <li className="flex items-center">
                <Check className="h-5 w-5 text-primary-200 mr-3" />
                Advanced analytics
              </li>
              <li className="flex items-center">
                <Check className="h-5 w-5 text-primary-200 mr-3" />
                Priority support
              </li>
            </ul>
            <Button className="w-full bg-white text-primary-600 hover:bg-gray-100" asChild>
              <a href="/upgrade">Upgrade Now</a>
            </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-12">
        <div className="container mx-auto px-4">
          <div className="flex items-center justify-center space-x-2 mb-8">
            <Dumbbell className="h-8 w-8 text-primary-400" />
            <span className="text-2xl font-bold">FitForge</span>
          </div>
          <div className="text-center text-gray-400">
            <p>&copy; 2024 FitForge. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  )
}
